------------------------------- MODULE MC -------------------------------
<%#
/*
 * An EJS template for generating the initial state from the aggregated state of the contract.
 *
 * Usage:
 *
 * npx ejs MCxycloans_monitor.ejs.tla -f state.json >MC.tla
 *
 * Igor Konnov, 2024
 */
%>
(* THIS MODULE IS AUTOGENERATED FROM SOROBAN STATE *)
EXTENDS Integers, Apalache, xycloans_types

\* the set of all possible token amounts
AMOUNTS == Nat
\* the contract address for the xycLoans contract
XYCLOANS == "<%- contractId %>"
\* the token address
XLM_TOKEN_SAC_TESTNET == "<%- storage[contractId].instance.TokenId %>"

\* user-controlled addresses
USER_ADDR == {
    <%
    const balanceAddrs =
        Object.keys(storage[contractId].persistent)
            .filter((key) => key.startsWith("Balance,"))
            .map((key) => key.split(",")[1])
    const tokenAddrs =
        Object.keys(storage[storage[contractId].instance.TokenId].persistent)
            .filter((key) => key.startsWith("Balance,"))
            .filter((key) => key !== `Balance,${contractId}`)
            .map((key) => key.split(",")[1])
    %>
    <%-
    [...new Set(balanceAddrs.concat(tokenAddrs))]
        .map((addr) => `    "${addr}"`)
        .join(",\n    ")
    %>
  }

\* the pool of addresses to draw the values from
ADDR == { XYCLOANS, XLM_TOKEN_SAC_TESTNET } \union USER_ADDR

VARIABLES
    \* @type: $tx;
    last_tx,
    \* @type: Str -> Int;
    shares,
    \* @type: Int;
    total_shares,
    \* @type: Int;
    fee_per_share_universal,
    \* Keep track of the current storage,
    \* which can be only changed by a successful transaction.
    \* @type: $storage;
    storage

INSTANCE xycloans_monitor

Init ==
    LET init_stor == [
        self_instance |-> [
            FeePerShareUniversal |-> <%- storage[contractId].instance.FeePerShareUniversal %>,
            TokenId |-> "<%- storage[contractId].instance.TokenId %>"
        ],
        self_persistent |-> [
            Balance |-> SetAsFun({<%-
              Object.keys(storage[contractId].persistent)
                .filter((key) => key.startsWith("Balance,"))
                .map((key) => key.split(",")[1])
                .map((addr) => `<<"${addr}", ${storage[contractId].persistent["Balance," + addr]}>>`)
                .join(",\n              ")
            %>}),
            MaturedFeesParticular |-> SetAsFun({<%-
              Object.keys(storage[contractId].persistent)
                .filter((key) => key.startsWith("MaturedFeesParticular,"))
                .map((key) => key.split(",")[1])
                .map((addr) => `<<"${addr}", ${storage[contractId].persistent["MaturedFeesParticular," + addr]}>>`)
                .join(",\n              ")
            %>}),
            FeePerShareParticular |-> SetAsFun({<%-
              Object.keys(storage[contractId].persistent)
                .filter((key) => key.startsWith("FeePerShareParticular,"))
                .map((key) => key.split(",")[1])
                .map((addr) => `<<"${addr}", ${storage[contractId].persistent["FeePerShareParticular," + addr]}>>`)
                .join(",\n              ")
            %>})
        ],
        token_persistent |-> [ Balance |-> SetAsFun({<%-
              Object.keys(storage[storage[contractId].instance.TokenId].persistent)
                .filter((key) => key.startsWith("Balance,"))
                .map((key) => key.split(",")[1])
                .map((addr) =>
                  `<<"${addr}", ${storage[storage[contractId].instance.TokenId].persistent["Balance," + addr].amount}>>`)
                .join(",\n              ")
        %>})]
    ]
    IN
    \* initialize the monitor non-deterministically
    /\ shares \in [ USER_ADDR -> Nat ]
    /\ total_shares \in Nat
    /\ fee_per_share_universal \in Nat
    \* initialize the contract state that we model
    /\ last_tx = [
            call |-> Constructor(XYCLOANS),
            status |-> TRUE,
            env |-> [
                current_contract_address |-> XYCLOANS,
                storage |-> init_stor,
                old_storage |-> init_stor
            ]
        ]
    /\ storage = init_stor

Next ==
    \* Generate some values for the storage.
    \* For value generation, we go over all addresses, not subsets of addresses.
    \E fpsu \in AMOUNTS, tid \in { "", XLM_TOKEN_SAC_TESTNET }:
      \E b, mfp, fpsp, tb \in [ ADDR -> AMOUNTS ]:
        LET new_stor == [
                self_instance |-> [ FeePerShareUniversal |-> fpsu, TokenId |-> tid ],
                self_persistent |->
                    [ Balance |-> b, MaturedFeesParticular |-> mfp, FeePerShareParticular |-> fpsp ],
                token_persistent |-> [ Balance |-> tb ]
            ]
            env == [
                current_contract_address |-> XYCLOANS,
                storage |-> new_stor,
                old_storage |-> storage
            ]
        IN
        \E addr \in ADDR, amount \in AMOUNTS, success \in BOOLEAN:
            /\  \/ LET tx == [ env |-> env, call |-> Initialize(XLM_TOKEN_SAC_TESTNET), status |-> success ] IN
                   initialize(tx) /\ last_tx' = tx
                \/ LET tx == [ env |-> env, call |-> Deposit(addr, amount), status |-> success ] IN
                   deposit(tx) /\ last_tx' = tx
                \/ LET tx == [ env |-> env, call |-> Borrow(addr, amount), status |-> success ] IN
                   borrow(tx) /\ last_tx' = tx
                \/ LET tx == [ env |-> env, call |-> UpdateFeeRewards(addr), status |-> success ] IN
                   update_fee_rewards(tx) /\ last_tx' = tx
            /\ storage' = IF success THEN new_stor ELSE storage

\* restrict the executions to the successful transactions
NextOk ==
    Next /\ last_tx'.status

\* use this falsy invariant to generate examples of successful transactions
NoSuccessInv ==
    ~IsConstructor(last_tx.call) => ~last_tx.status

\* use this view to generate better test coverage
\* apalache-mc check --max-error=10 --length=10 --inv=NoSuccessInv --view=View MCxycloans_monitor.tla
View == <<last_tx.status, VariantTag(last_tx.call)>>
=========================================================================================