on:
  # Every pull request
  pull_request:
  push:
    branches:
      - main

name: build

jobs:
  unit-tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        # macos is burning my free minutes way too fast
        #operating-system: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: install npm dependencies
        run: cd ./solarkraft && npm ci
      - name: compile solarkraft
        run: cd ./solarkraft && npm run compile
      - name: unit tests
        run: cd ./solarkraft && npm run test

  housekeeping:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: install npm dependencies
        run: cd ./solarkraft && npm ci
      - name: eslint
        run: cd ./solarkraft && npm run lint
      - name: check license
        run: cd ./solarkraft && (npm run license | grep -v updated) || echo "fix with 'npm run license'"
      - name: check formatting
        run: cd ./solarkraft && (npx prettier --config .prettierrc --check src/**/*.ts test/**/*.ts) || echo "fix with 'npm run format'"

  contracts-unit-tests:
    name: contracts-unit-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup target add wasm32-unknown-unknown
      - uses: stellar/binaries@v16
        with:
          name: soroban-cli
          version: 0.8.7
      - name: build
        run: cd ContractExamples && cargo build --verbose
      - name: unit tests
        run: cd ContractExamples && cargo test --verbose
      - name: populating setter
        run: cd ContractExamples && ./scripts/setter-populate.sh