name: Deployment to testnet

on:
  workflow_dispatch:
  # TODO: comment out after debugging in the draft PR
  pull_request:
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update submodules
        run: |
          git submodule update --init --recursive
      # see: https://github.com/stellar/soroban-examples/blob/main/.github/workflows/rust.yml
      - uses: stellar/actions/rust-cache@main
      - run: rustup update
      - run: cargo version
      - run: rustup target add wasm32-unknown-unknown
      - uses: stellar/stellar-cli@main
        with:
          version: 22.0.0

      - name: Generate Soroban keys
        run: |
          stellar keys generate --global alice --network testnet --fund
          stellar keys generate --global bob --network testnet --fund

      - name: Build contract examples
        run: |
          cd ContractExamples
          cargo build --release --all

      - name: Deploy alert
        run: |
          cd ContractExamples
          ./scripts/alert-deploy.sh

      - name: Deploy timelock
        run: |
          cd ContractExamples
          ./scripts/prepare-timelock.sh

      - name: Deploy setter
        run: |
          cd ContractExamples
          ./scripts/setter-populate.sh

      #- uses: actions/setup-node@v3
      #  with:
      #    node-version: '16'
      #   stellar keys generate --global admin --network testnet --fund